name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Configure CI Git User
        run: |
          git config --global user.email wild-bot@github.com
          git config --global user.name GitHub Actions
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo //registry.wild.plus/:_authToken=${{ secrets.NPM_TOKEN }} > .npmrc
      - run: yarn install
      - run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}